[alias]
ta = ["test", "--all-features", "--all"]
clip = ["clippy", "--all-features"]
open-doc = [
    "test",
    # "--package",
    # "tests",
    "--test",
    "doc",
    "--all-features",
    "--",
    "build_and_open_rust_doc",
    "--exact",
    "--show-output",
    "--ignored",
]
